// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hla_sort
std::vector<std::string> hla_sort(std::vector<std::string> alleles);
RcppExport SEXP hlatools_hla_sort(SEXP allelesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type alleles(allelesSEXP);
    rcpp_result_gen = Rcpp::wrap(hla_sort(alleles));
    return rcpp_result_gen;
END_RCPP
}
// hla_allele_to_genotype
std::vector<std::string> hla_allele_to_genotype(std::vector<std::string> a1, std::vector<std::string> a2);
RcppExport SEXP hlatools_hla_allele_to_genotype(SEXP a1SEXP, SEXP a2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type a2(a2SEXP);
    rcpp_result_gen = Rcpp::wrap(hla_allele_to_genotype(a1, a2));
    return rcpp_result_gen;
END_RCPP
}
// field1
std::vector<std::string> field1(std::vector<std::string> a);
RcppExport SEXP hlatools_field1(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(field1(a));
    return rcpp_result_gen;
END_RCPP
}
// field2
std::vector<std::string> field2(std::vector<std::string> a);
RcppExport SEXP hlatools_field2(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(field2(a));
    return rcpp_result_gen;
END_RCPP
}
