# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sort HLA alleles by field
#'
#' @param alleles A vector of HLA alleles.
#' @return A sorted vector of HLA alleles.
#' @export
hla_sort <- function(alleles) {
    .Call('hlatools_hla_sort', PACKAGE = 'hlatools', alleles)
}

hla_allele_to_genotype <- function(a1, a2) {
    .Call('hlatools_hla_allele_to_genotype', PACKAGE = 'hlatools', a1, a2)
}

field1 <- function(a) {
    .Call('hlatools_field1', PACKAGE = 'hlatools', a)
}

field2 <- function(a) {
    .Call('hlatools_field2', PACKAGE = 'hlatools', a)
}

